ome/ansible-role-omero-server

example.yml, molecule.yml, tests/playbook.yml
This means you can link directly to `example.yml`
See https://github.com/openmicroscopy/infrastructure/pull/246#discussion_r98951975
=> Split playbook into example.yml and tests/playbook.yml

tasks/omero-user.yml
> necessary to make training-server.yml run on CentOS 7 in (Vagrant box 1611.01 for VirtualBox).
Migrated from https://github.com/openmicroscopy/infrastructure/pull/244
=> create /home/omero/.bashrc if it does not exist

README.md
Couple of Typos left over from openmicroscopy.ansible-role-omero-web
=> Typos left over from openmicroscopy.ansible-role-omero-web

tests/requirements.yml
Following https://github.com/ansible/galaxy-issues/issues/259, using GitHub should no longer be required.
=> Use upstream openmicroscopy.omero-common

README.md, defaults/main.yml, tasks/omero-datadir.yml
Ideally there would be a property along the lines of `omero.bioformatscache.dir`. Since there isn't this new option `omero_server_datadir_bioformatscache` creates a symlink under `omero.data.dir`
Tag: `2.0.0-m3`
=> Allow alternative location for BioFormatsCache

README.md, defaults/main.yml, molecule.yml, playbook.yml, tasks/omero-install.yml, tests/test_newdep.py
This adds the ability to convert `https://downloads.openmicroscopy.org/latest/omero` into a release number. This means for normal installations the value of `omero_server_release` is sufficient to control whether a server is upgraded or not. The `omero_server_upgrade` is therefore changed to `True` and deprecated. The only reason for not removing it at the moment is that the IDR uses a non-standard version system where the version in the URL is not the version reported by the server. This could be remedied by https://trello.com/c/NbdI5wVn/62-release-artifacts-json-scoping since the URL version and the version in  the release-artifacts.json file could be different.
=> Parse latest release from downloads url, upgrade by default

README.md, tests/test_newdep.py
Fixes #19 
The primary goal of this PR is to fix the currently the failing Travis tests for the omero.server Ansible role since the release of OMERO 5.4.0.
As the scope of the test is primarily to check that a initial OMERO 5.2 server is upgraded, the assertion is modified to test that the new server version is 5.3.0 or later. This should make the check independent of the latest major & minor version numbers of OMERO and reduce the maintenance burden.
Additionally badges are added to the README linking to the CI build and the Galaxy role.
=> Travis fix

playbook.yml
https://travis-ci.org/openmicroscopy/ome-ansible-molecule-dependencies/builds/319697019
began failing for some reason with only the old dependency not
properly starting. Digging into Blitz-0.log locally, one sees
that Ice is not able to communicate.
This fix could be more cleanly refactored into making the property
a must for all docker tests.
cc: @sbesson @manics
=> Add IPv6 to molecule tests

templates/00-omero-server-omero.j2
Python dict keys are unordered. This change ensures the addition or removal of keys will not change the order of existing configuration lines. If this is run on an existing server the config lines will be reordered.
Resolves https://github.com/openmicroscopy/ansible-role-omero-server/issues/25
Minor fix, tag `2.0.3`
=> Ensure config dict keys are sorted for idempotence

tests/test_default.py, tests/test_import.py
The Java security changes disabling anonymous cyphers have now been propagated to the openjdk and package managers and causes CLI imports via the CLI to fail with a `SSLHandshakeException` - see https://travis-ci.org/ome/ansible-roles/jobs/514734263
With OMERO 5.4.10, the workaround is to skip the upgrade check at import time. This means the role import tests can no longer be run on older servers. It is thus moved to a separate test file and restricted to the test hosts upgraded to the latest version.
=> Fix failing import test following Java release

README.md
Unstable/expert parameters are already documented in `defaults/main.yml`.
In line with other roles these parameters are not documented in the README.
=> Remove unstable section of README

.travis.yml, README.md, defaults/main.yml, molecule/newdep/molecule.yml, molecule/resources/install-novenv.yml, molecule/resources/tests/test_default.py, molecule/resources/tests/test_import.py, molecule/resources/tests/test_newdep.py, molecule/resources/tests/test_olddep.py, molecule/upgradetovenv/Dockerfile.j2, molecule/upgradetovenv/molecule.yml, tasks/omero-install.yml, templates/omero-server-config-update-sh.j2, templates/systemd-system-omero-server-service.j2
Installs and runs OMERO.server from a virtualenv `/opt/omero/server/venv`
New parameter `omero_server_python_addons` that can be used to install addons at the same time, though it's also fine to install addons into the virtualenv separately.
Default behaviour is unchanged (no virtualenv) though we should consider switching this as we start encouraging people to install decoupled components.
Includes a `no-venv → venv` test.
=> Install OMERO.server in a virtualenv

tasks/omero-install.yml
Non-standard strings (e.g. CI job names) can no longer be compared against versions. Since this usually indicates a CI build unconditionanally upgrade.
Also fixes a deprecation warning:
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using
`result|version_compare` use `result is version_compare`. This feature will be
removed in version 2.9. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
=>  Fix Ansible version_compare change in behaviour

defaults/main.yml, molecule/resources/playbook-py3.yml, tasks/omero-install.yml
As a result of https://github.com/ome/openmicroscopy/pull/6200,
the bin directory is no longer being created leading to a build
failure in https://github.com/ome/omero-server-docker/pull/41
=> Re-create bin directory for omero wrapper

defaults/main.yml
This should force omero-py 5.6.dev releases to be upgraded to at least 5.6.0
Also force dropbox to be upgraded to the to-be-released 5.6.1 bugfix (travis will fail until it's released).
=> _omero_py_version>=5.6.0 _omero_dropbox_version>=5.6.1

README.md, defaults/main.yml, templates/systemd-system-omero-server-service.j2
Enables arbitrary extra environment variables to be set when running OMERO.server with systemd.
This is an attempt to workaround https://github.com/ome/omero-web/issues/118
=> Add omero_server_systemd_environment to systemd service

README.md, meta/main.yml, molecule/resources/install-novenv.yml, molecule/resources/install-oldomero.yml, molecule/resources/playbook-py3.yml, molecule/resources/requirements.yml
Uses the new `ome.postgresql_client` instead of overriding `postgresql_install_server` in `ome.postgresql`
Tag: Not sure, maybe `3.2.0`, I don't think it's a breaking change.
This should be released before https://github.com/ome/ansible-role-postgresql/pull/19 is released to avoid errors for anyone who hasn't pinned their roles to a fixed version. This is due to the removal of `postgresql_install_server: False` (`postgresql_install_server: True` is no-op).
=> Use ome.postgresql_client

molecule/resources/playbook-py3.yml
Try removing the hardcoded pinning to a release candidate version of the server in one of the Molecule tests
=> Do not pin OMERO.server version to 5.6.0-rc1 in Molecule

molecule/centos7/molecule.yml, tasks/omero-install.yml
Fixes https://github.com/ome/ansible-role-omero-server/issues/57
As a result of TLS 1.0/1.1 being now disabled by default in OpenJDK incl. 8 and 11, all base CentOS 7 installations start failing import with a `SSLHandshakeException`.
This PR configures `omero-certificates` to generate self-signed certificates exactly like what is currently done in Ubuntu 18.04 and Ubuntu 20.04. This seems to be sufficient to fix the failing import tests.
Note 900548e ensures `openssl` is installed on the system but I suspect we might want to push this installation down to [ome.basedeps](https://github.com/ome/ansible-role-basedeps). Opening this PR as it is anyways to start the discussion
=> CentOS 7: configure omero-certificates

defaults/main.yml
The tables are installed by default since the removal of Ubuntu 16.04 support
=> simplify installation of omero-cli-server

meta/requirements.yml, tasks/pre-tasks.yml
This PR removes include `PostgreSQL `role. It is redundant and needed only for molecular tests so, it should not included in the `requirements.yml` inside `meta` folded or pre-task.yml inside `tasks`.
This was one of the causes of the Rokcylinux image-building failure.
I have pushed it to the `ansible-galaxy`, i.e.  `khaledk2.omero_server`.
I have created a branch on my omero-server-docker fork (https://github.com/khaledk2/omero-server-docker/tree/build_rocky9)  based on https://github.com/jburel/omero-server-docker/tree/ubuntu22.04, I have used the modified omero-server-role and made the required modifications to make it build the RockyLinux 9 image.
It has built the image successfully and passed the tests on: 
https://github.com/khaledk2/omero-server-docker/actions/runs/6922804692
cc …
=> Fix include 

README.md, molecule/resources/playbook.yml
This PR adds the database owner to fix the following error 
`ERROR:  permission denied for schema public`
This causes a failure of the latest molecule test
https://github.com/ome/ansible-role-omero-server/actions/runs/8040907812/job/21959550545#step:5:1572
https://github.com/ome/ansible-role-omero-server/actions/runs/8040907812/job/21959550625#step:5:1537
=> Fix Molecule 

tasks/omero-install.yml
See https://github.com/IDR/deployment/issues/433 for the motivation
This flag creates an unnecessary overhead for every package installation task
=> Do not force the update of the dnf cache
